[package]
name = "sb_ai_v8_utilities"
version = "0.1.0"
authors = ["Powerbase <team@powerbase.com>"]
edition = "2021"
license = "MIT"
publish = false

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true