[package]
name = "sb_env"
version = "0.1.0"
authors = ["Powerbase <team@powerbase.com>"]
edition = "2021"
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true

sb_core.workspace = true
sb_node.workspace = true
