[env]
# https://powerbase.com/docs/guides/functions/limits
POWERBASE_RESOURCE_LIMIT_MEM_MB = "256"
POWERBASE_RESOURCE_LIMIT_LOW_MEM_MULTIPLIER = "5"
POWERBASE_RESOURCE_LIMIT_CPU_SOFT_MS = "1000"
POWERBASE_RESOURCE_LIMIT_CPU_HARD_MS = "2000"
POWERBASE_RESOURCE_LIMIT_TIMEOUT_MS = "400000"
